"""Plantilla base para generar migraciones

feat(T-014): agregar tabla plantas

Revision ID: 040ab409674b
Revises: 778b31b200bd
Create Date: 2025-10-12 20:43:08.055425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '040ab409674b'
down_revision = '778b31b200bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la planta'),
    sa.Column('usuario_id', sa.Integer(), nullable=False, comment='ID del usuario propietario de la planta'),
    sa.Column('especie_id', sa.Integer(), nullable=True, comment='ID de la especie de la planta (opcional)'),
    sa.Column('nombre_personal', sa.String(length=255), nullable=False, comment='Nombre personalizado dado por el usuario'),
    sa.Column('estado_salud', sa.String(length=50), nullable=False, comment='Estado de salud: excelente, buena, necesita_atencion, critica'),
    sa.Column('ubicacion', sa.String(length=255), nullable=True, comment='Ubicación física de la planta'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales del usuario'),
    sa.Column('imagen_principal_id', sa.Integer(), nullable=True, comment='ID de la imagen principal de la planta'),
    sa.Column('fecha_ultimo_riego', sa.DateTime(), nullable=True, comment='Fecha y hora del último riego'),
    sa.Column('proxima_riego', sa.DateTime(), nullable=True, comment='Fecha y hora del próximo riego recomendado'),
    sa.Column('frecuencia_riego_dias', sa.Integer(), nullable=True, comment='Frecuencia de riego en días'),
    sa.Column('luz_actual', sa.String(length=20), nullable=True, comment='Nivel de luz que recibe: baja, media, alta, directa'),
    sa.Column('fecha_adquisicion', sa.DateTime(), nullable=True, comment='Fecha en que el usuario adquirió la planta'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de última actualización'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si la planta está activa (no eliminada)'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plantas', schema=None) as batch_op:
        batch_op.create_index('idx_created_at_plantas', ['created_at'], unique=False)
        batch_op.create_index('idx_proxima_riego', ['proxima_riego'], unique=False)
        batch_op.create_index('idx_usuario_estado_salud', ['usuario_id', 'estado_salud'], unique=False)
        batch_op.create_index('idx_usuario_plantas_activas', ['usuario_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plantas_especie_id'), ['especie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plantas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plantas_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('identificaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_especie_confianza')
        batch_op.drop_index('idx_imagen_especie')
        batch_op.drop_index('idx_origen')
        batch_op.drop_index('idx_usuario_identificacion')
        batch_op.drop_index('idx_validado')
        batch_op.drop_index('ix_identificaciones_especie_id')
        batch_op.drop_index('ix_identificaciones_id')
        batch_op.drop_index('ix_identificaciones_imagen_id')
        batch_op.drop_index('ix_identificaciones_usuario_id')

    # Eliminar la foreign key constraint de imagenes antes de eliminar identificaciones
    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imagenes_identificacion_id', type_='foreignkey')
    
    op.drop_table('identificaciones')
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.drop_index('idx_especies_active')
        batch_op.drop_index('idx_familia')
        batch_op.drop_index('idx_nivel_dificultad')
        batch_op.drop_index('idx_nombre_cientifico')
        batch_op.drop_index('idx_nombre_comun')
        batch_op.drop_index('ix_especies_familia')
        batch_op.drop_index('ix_especies_id')
        batch_op.drop_index('ix_especies_nombre_cientifico')
        batch_op.drop_index('ix_especies_nombre_comun')

    op.drop_table('especies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('especies_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Identificador único de la especie'),
    sa.Column('nombre_comun', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nombre común de la planta'),
    sa.Column('nombre_cientifico', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nombre científico de la especie (único)'),
    sa.Column('familia', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Familia botánica'),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True, comment='Descripción general de la planta'),
    sa.Column('cuidados_basicos', sa.TEXT(), autoincrement=False, nullable=True, comment='Instrucciones básicas de cuidado en formato JSON'),
    sa.Column('nivel_dificultad', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Nivel de dificultad: facil, medio, dificil'),
    sa.Column('luz_requerida', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Requerimientos de luz: baja, media, alta, directa'),
    sa.Column('riego_frecuencia', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Frecuencia de riego recomendada'),
    sa.Column('temperatura_min', sa.INTEGER(), autoincrement=False, nullable=True, comment='Temperatura mínima tolerable en °C'),
    sa.Column('temperatura_max', sa.INTEGER(), autoincrement=False, nullable=True, comment='Temperatura máxima tolerable en °C'),
    sa.Column('humedad_requerida', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Nivel de humedad: baja, media, alta'),
    sa.Column('toxicidad', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Nivel de toxicidad: no_toxica, leve, moderada, alta'),
    sa.Column('origen_geografico', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Región de origen de la especie'),
    sa.Column('imagen_referencia_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='URL de imagen de referencia de la especie'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Fecha de última actualización'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Indica si la especie está activa en el catálogo'),
    sa.PrimaryKeyConstraint('id', name='especies_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.create_index('ix_especies_nombre_comun', ['nombre_comun'], unique=False)
        batch_op.create_index('ix_especies_nombre_cientifico', ['nombre_cientifico'], unique=False)
        batch_op.create_index('ix_especies_id', ['id'], unique=False)
        batch_op.create_index('ix_especies_familia', ['familia'], unique=False)
        batch_op.create_index('idx_nombre_comun', ['nombre_comun'], unique=False)
        batch_op.create_index('idx_nombre_cientifico', ['nombre_cientifico'], unique=False)
        batch_op.create_index('idx_nivel_dificultad', ['nivel_dificultad'], unique=False)
        batch_op.create_index('idx_familia', ['familia'], unique=False)
        batch_op.create_index('idx_especies_active', ['is_active'], unique=False)

    op.create_table('identificaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Identificador único de la identificación'),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID del usuario que realizó/recibió la identificación'),
    sa.Column('imagen_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID de la imagen analizada'),
    sa.Column('especie_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID de la especie identificada'),
    sa.Column('confianza', sa.INTEGER(), autoincrement=False, nullable=False, comment='Nivel de confianza de la identificación (0-100)'),
    sa.Column('origen', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Origen: ia_plantnet, ia_local, manual'),
    sa.Column('validado', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Indica si fue validada por el usuario'),
    sa.Column('notas_usuario', sa.TEXT(), autoincrement=False, nullable=True, comment='Notas adicionales del usuario'),
    sa.Column('metadatos_ia', sa.TEXT(), autoincrement=False, nullable=True, comment='Metadatos del proceso de IA en formato JSON'),
    sa.Column('fecha_identificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Fecha y hora de la identificación'),
    sa.Column('fecha_validacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Fecha y hora de validación por usuario'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['especie_id'], ['especies.id'], name='identificaciones_especie_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagenes.id'], name='identificaciones_imagen_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='identificaciones_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='identificaciones_pkey')
    )
    with op.batch_alter_table('identificaciones', schema=None) as batch_op:
        batch_op.create_index('ix_identificaciones_usuario_id', ['usuario_id'], unique=False)
        batch_op.create_index('ix_identificaciones_imagen_id', ['imagen_id'], unique=False)
        batch_op.create_index('ix_identificaciones_id', ['id'], unique=False)
        batch_op.create_index('ix_identificaciones_especie_id', ['especie_id'], unique=False)
        batch_op.create_index('idx_validado', ['validado'], unique=False)
        batch_op.create_index('idx_usuario_identificacion', ['usuario_id', 'fecha_identificacion'], unique=False)
        batch_op.create_index('idx_origen', ['origen'], unique=False)
        batch_op.create_index('idx_imagen_especie', ['imagen_id', 'especie_id'], unique=False)
        batch_op.create_index('idx_especie_confianza', ['especie_id', 'confianza'], unique=False)

    with op.batch_alter_table('plantas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_plantas_id'))
        batch_op.drop_index(batch_op.f('ix_plantas_especie_id'))
        batch_op.drop_index('idx_usuario_plantas_activas')
        batch_op.drop_index('idx_usuario_estado_salud')
        batch_op.drop_index('idx_proxima_riego')
        batch_op.drop_index('idx_created_at_plantas')

    op.drop_table('plantas')
    # ### end Alembic commands ###