"""Plantilla base para generar migraciones

feat: agregar tablas especies e identificaciones

Revision ID: 3ab5c396ba90
Revises: 040ab409674b
Create Date: 2025-10-12 21:15:35.541465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab5c396ba90'
down_revision = '040ab409674b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especies',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la especie'),
    sa.Column('nombre_comun', sa.String(length=255), nullable=False, comment='Nombre común de la especie'),
    sa.Column('nombre_cientifico', sa.String(length=255), nullable=False, comment='Nombre científico (único)'),
    sa.Column('familia', sa.String(length=255), nullable=True, comment='Familia taxonómica'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción detallada de la especie'),
    sa.Column('cuidados_basicos', sa.Text(), nullable=True, comment='JSON con cuidados básicos'),
    sa.Column('nivel_dificultad', sa.String(length=50), nullable=False, comment='Nivel de dificultad: facil, medio, dificil'),
    sa.Column('luz_requerida', sa.String(length=50), nullable=True, comment='Nivel de luz: baja, media, alta'),
    sa.Column('riego_frecuencia', sa.String(length=255), nullable=True, comment='Descripción de frecuencia de riego'),
    sa.Column('temperatura_min', sa.Integer(), nullable=True, comment='Temperatura mínima en grados Celsius'),
    sa.Column('temperatura_max', sa.Integer(), nullable=True, comment='Temperatura máxima en grados Celsius'),
    sa.Column('humedad_requerida', sa.String(length=50), nullable=True, comment='Nivel de humedad: baja, media, alta'),
    sa.Column('toxicidad', sa.String(length=50), nullable=True, comment='Nivel de toxicidad: ninguna, leve, moderada, alta'),
    sa.Column('origen_geografico', sa.String(length=255), nullable=True, comment='Región geográfica de origen'),
    sa.Column('imagen_referencia_url', sa.String(length=500), nullable=True, comment='URL de imagen de referencia'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de última actualización'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si la especie está activa'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.create_index('idx_especie_activa', ['is_active'], unique=False)
        batch_op.create_index('idx_especie_dificultad', ['nivel_dificultad'], unique=False)
        batch_op.create_index('idx_especie_familia', ['familia'], unique=False)
        batch_op.create_index(batch_op.f('ix_especies_familia'), ['familia'], unique=False)
        batch_op.create_index(batch_op.f('ix_especies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_especies_nombre_cientifico'), ['nombre_cientifico'], unique=True)
        batch_op.create_index(batch_op.f('ix_especies_nombre_comun'), ['nombre_comun'], unique=False)

    op.create_table('identificaciones',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único'),
    sa.Column('usuario_id', sa.Integer(), nullable=False, comment='ID del usuario'),
    sa.Column('imagen_id', sa.Integer(), nullable=False, comment='ID de la imagen'),
    sa.Column('especie_id', sa.Integer(), nullable=True, comment='ID de la especie identificada'),
    sa.Column('confianza', sa.Integer(), nullable=False, comment='Nivel de confianza (0-100)'),
    sa.Column('origen', sa.String(length=50), nullable=False, comment='Origen: ia_plantnet, manual'),
    sa.Column('validado', sa.Boolean(), nullable=False, comment='Si fue validado por el usuario'),
    sa.Column('fecha_identificacion', sa.DateTime(), nullable=False, comment='Fecha de la identificación'),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True, comment='Fecha de validación por el usuario'),
    sa.Column('notas_usuario', sa.Text(), nullable=True, comment='Notas del usuario sobre la identificación'),
    sa.Column('metadatos_ia', sa.Text(), nullable=True, comment='JSON con metadatos de la IA (score, versión, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de actualización'),
    sa.ForeignKeyConstraint(['especie_id'], ['especies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identificaciones', schema=None) as batch_op:
        batch_op.create_index('idx_identificacion_especie', ['especie_id'], unique=False)
        batch_op.create_index('idx_identificacion_fecha', ['fecha_identificacion'], unique=False)
        batch_op.create_index('idx_identificacion_imagen', ['imagen_id'], unique=False)
        batch_op.create_index('idx_identificacion_origen', ['origen'], unique=False)
        batch_op.create_index('idx_identificacion_usuario', ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_especie_id'), ['especie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_imagen_id'), ['imagen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identificaciones_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_identificaciones_imagen_id'))
        batch_op.drop_index(batch_op.f('ix_identificaciones_id'))
        batch_op.drop_index(batch_op.f('ix_identificaciones_especie_id'))
        batch_op.drop_index('idx_identificacion_usuario')
        batch_op.drop_index('idx_identificacion_origen')
        batch_op.drop_index('idx_identificacion_imagen')
        batch_op.drop_index('idx_identificacion_fecha')
        batch_op.drop_index('idx_identificacion_especie')

    op.drop_table('identificaciones')
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_especies_nombre_comun'))
        batch_op.drop_index(batch_op.f('ix_especies_nombre_cientifico'))
        batch_op.drop_index(batch_op.f('ix_especies_id'))
        batch_op.drop_index(batch_op.f('ix_especies_familia'))
        batch_op.drop_index('idx_especie_familia')
        batch_op.drop_index('idx_especie_dificultad')
        batch_op.drop_index('idx_especie_activa')

    op.drop_table('especies')
    # ### end Alembic commands ###