"""Plantilla base para generar migraciones

feat(T-017): agregar modelos Especie e Identificacion

Revision ID: 778b31b200bd
Revises: 002_add_imagenes_table
Create Date: 2025-10-12 20:15:04.339256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '778b31b200bd'
down_revision = '002_add_imagenes_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especies',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la especie'),
    sa.Column('nombre_comun', sa.String(length=255), nullable=False, comment='Nombre común de la planta'),
    sa.Column('nombre_cientifico', sa.String(length=255), nullable=False, comment='Nombre científico de la especie (único)'),
    sa.Column('familia', sa.String(length=100), nullable=True, comment='Familia botánica'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción general de la planta'),
    sa.Column('cuidados_basicos', sa.Text(), nullable=True, comment='Instrucciones básicas de cuidado en formato JSON'),
    sa.Column('nivel_dificultad', sa.String(length=20), nullable=False, comment='Nivel de dificultad: facil, medio, dificil'),
    sa.Column('luz_requerida', sa.String(length=20), nullable=True, comment='Requerimientos de luz: baja, media, alta, directa'),
    sa.Column('riego_frecuencia', sa.String(length=100), nullable=True, comment='Frecuencia de riego recomendada'),
    sa.Column('temperatura_min', sa.Integer(), nullable=True, comment='Temperatura mínima tolerable en °C'),
    sa.Column('temperatura_max', sa.Integer(), nullable=True, comment='Temperatura máxima tolerable en °C'),
    sa.Column('humedad_requerida', sa.String(length=20), nullable=True, comment='Nivel de humedad: baja, media, alta'),
    sa.Column('toxicidad', sa.String(length=20), nullable=True, comment='Nivel de toxicidad: no_toxica, leve, moderada, alta'),
    sa.Column('origen_geografico', sa.String(length=255), nullable=True, comment='Región de origen de la especie'),
    sa.Column('imagen_referencia_url', sa.String(length=500), nullable=True, comment='URL de imagen de referencia de la especie'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de última actualización'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si la especie está activa en el catálogo'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.create_index('idx_especies_active', ['is_active'], unique=False)
        batch_op.create_index('idx_familia', ['familia'], unique=False)
        batch_op.create_index('idx_nivel_dificultad', ['nivel_dificultad'], unique=False)
        batch_op.create_index('idx_nombre_cientifico', ['nombre_cientifico'], unique=False)
        batch_op.create_index('idx_nombre_comun', ['nombre_comun'], unique=False)
        batch_op.create_index(batch_op.f('ix_especies_familia'), ['familia'], unique=False)
        batch_op.create_index(batch_op.f('ix_especies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_especies_nombre_cientifico'), ['nombre_cientifico'], unique=True)
        batch_op.create_index(batch_op.f('ix_especies_nombre_comun'), ['nombre_comun'], unique=False)

    op.create_table('identificaciones',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la identificación'),
    sa.Column('usuario_id', sa.Integer(), nullable=False, comment='ID del usuario que realizó/recibió la identificación'),
    sa.Column('imagen_id', sa.Integer(), nullable=False, comment='ID de la imagen analizada'),
    sa.Column('especie_id', sa.Integer(), nullable=False, comment='ID de la especie identificada'),
    sa.Column('confianza', sa.Integer(), nullable=False, comment='Nivel de confianza de la identificación (0-100)'),
    sa.Column('origen', sa.String(length=50), nullable=False, comment='Origen: ia_plantnet, ia_local, manual'),
    sa.Column('validado', sa.Boolean(), nullable=False, comment='Indica si fue validada por el usuario'),
    sa.Column('notas_usuario', sa.Text(), nullable=True, comment='Notas adicionales del usuario'),
    sa.Column('metadatos_ia', sa.Text(), nullable=True, comment='Metadatos del proceso de IA en formato JSON'),
    sa.Column('fecha_identificacion', sa.DateTime(), nullable=False, comment='Fecha y hora de la identificación'),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True, comment='Fecha y hora de validación por usuario'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['especie_id'], ['especies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identificaciones', schema=None) as batch_op:
        batch_op.create_index('idx_especie_confianza', ['especie_id', 'confianza'], unique=False)
        batch_op.create_index('idx_imagen_especie', ['imagen_id', 'especie_id'], unique=False)
        batch_op.create_index('idx_origen', ['origen'], unique=False)
        batch_op.create_index('idx_usuario_identificacion', ['usuario_id', 'fecha_identificacion'], unique=False)
        batch_op.create_index('idx_validado', ['validado'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_especie_id'), ['especie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_imagen_id'), ['imagen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identificaciones_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.alter_column('container_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_comment='Nombre del contenedor de Azure donde está almacenada',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='Fecha y hora de subida de la imagen',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='Fecha y hora de última actualización',
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Soft delete - indica si la imagen fue eliminada lógicamente',
               existing_nullable=False)
        batch_op.drop_constraint('uq_imagenes_nombre_blob', type_='unique')
        batch_op.drop_index('ix_imagenes_nombre_blob')
        batch_op.create_index(batch_op.f('ix_imagenes_nombre_blob'), ['nombre_blob'], unique=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='Fecha y hora de creación de la cuenta',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='Fecha y hora de última actualización',
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Estado de activación de la cuenta',
               existing_nullable=False)
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Indica si el usuario tiene privilegios de administrador',
               existing_nullable=False)
        batch_op.drop_constraint('uq_usuarios_email', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_usuarios_email', ['email'])
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Indica si el usuario tiene privilegios de administrador',
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Estado de activación de la cuenta',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='Fecha y hora de última actualización',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='Fecha y hora de creación de la cuenta',
               existing_nullable=False)

    with op.batch_alter_table('imagenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imagenes_nombre_blob'))
        batch_op.create_index('ix_imagenes_nombre_blob', ['nombre_blob'], unique=False)
        batch_op.create_unique_constraint('uq_imagenes_nombre_blob', ['nombre_blob'])
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Soft delete - indica si la imagen fue eliminada lógicamente',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='Fecha y hora de última actualización',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='Fecha y hora de subida de la imagen',
               existing_nullable=False)
        batch_op.alter_column('container_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'plantitas-imagenes'::character varying"),
               existing_comment='Nombre del contenedor de Azure donde está almacenada',
               existing_nullable=False)

    with op.batch_alter_table('identificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identificaciones_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_identificaciones_imagen_id'))
        batch_op.drop_index(batch_op.f('ix_identificaciones_id'))
        batch_op.drop_index(batch_op.f('ix_identificaciones_especie_id'))
        batch_op.drop_index('idx_validado')
        batch_op.drop_index('idx_usuario_identificacion')
        batch_op.drop_index('idx_origen')
        batch_op.drop_index('idx_imagen_especie')
        batch_op.drop_index('idx_especie_confianza')

    op.drop_table('identificaciones')
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_especies_nombre_comun'))
        batch_op.drop_index(batch_op.f('ix_especies_nombre_cientifico'))
        batch_op.drop_index(batch_op.f('ix_especies_id'))
        batch_op.drop_index(batch_op.f('ix_especies_familia'))
        batch_op.drop_index('idx_nombre_comun')
        batch_op.drop_index('idx_nombre_cientifico')
        batch_op.drop_index('idx_nivel_dificultad')
        batch_op.drop_index('idx_familia')
        batch_op.drop_index('idx_especies_active')

    op.drop_table('especies')
    # ### end Alembic commands ###